### ISSUE TITLE
What is the use case for the babel build step?

### ISSUE THREAD

**Issue by thisismydesign** [flexdinesh/npm-module-boilerplate#5]
Hey,

I'm struggling to understand why your `build` step makes sense.

When using a package as a dependency from npm sometimes it's helpful to be able to look at the original code in `node_modules` (e.g. debugging an error coming from a dependency). Many editors let you navigate based on stacktrace, but finding a transpiled and minified version of the code will make debugging like this impossible.

As for the ES5 compatibility, whoever needs that will surely have a translation step in their build. For everyone else, this just makes the package code unreadable and adds a lot more size.

As for minifying, the performance impact highly depends on the size of the library. Again, whoever cares about this should minify their deliverable. And it again makes the package code unreadable.

Actually, in my case, the ES5 transpilation and minify together yields a bigger size than leaving the code as is, decreasing performance in that sense.

Am I missing something here?

**Comment by flexdinesh** [comment]
Here are a few reason why it's ideal to use Babel —
1. By default, bundlers don't transpile or minify the packages in `node_modules`. If the user needs to transpile something in the `node_modules` it has to be an explicit custom config.
2. To be able to look into the source code, we just have to publish the source code along with the module. To do that we remove the `src` entry in `.npmignore`. Not transpiling or minifying is not the ideal solution for "code transparency".
3. Transpilation definitely increases the package size but gives the freedom to write more readable code with latest specs.

I think the solution would be to make everything configurable so the users can choose the use or remove stuff based on their use case.

**Comment by thisismydesign** [comment]
Thanks, after looking into it some more I understand this issue goes much deeper than I thought and that the approach you're taking is the safest. [This approach](https://stackoverflow.com/a/52509974/2771889) could perhaps be a nice middle ground but I'm not sure about its implications in all environments. If you have time and interest in this topic that's more than welcome from my side, but otherwise you can close the issue.

**Comment by thisismydesign** [comment]
I concluded my investigation on the topic: https://github.com/c-hive/guides/blob/master/js/package.md#esm

I am by no means an expert, but from what I can tell, currently I wouldn't recommend anyone publishing anything but plain, fully backward compatible code.

**Comment by flexdinesh** [comment]
> I wouldn't recommend anyone publishing anything but plain, fully backward compatible code.

@thisismydesign You are absolutely right. When I created this repo, the community practices were different and a lot of things have changed since then. Will soon have to figure out a middle ground according to latest community practices and guidelines.
